#!/usr/bin/env bash
# Per-plugin README generator. Synthesises one README.md per
# crates/<name>/ from the crate's Cargo.toml + the marketplace
# catalogue entry (when present). Run from the repo root.
#
# Idempotent: re-runs overwrite the generated body but leave any
# hand-edited file alone if it lacks the generated marker line.
set -euo pipefail
cd "$(dirname "$0")/.."

MARKER="<!-- generated by scripts/gen-plugin-readmes.sh; do not edit by hand -->"

# Crate metadata lookup via grep — keeps this script dep-free for CI.
for crate in crates/*/; do
  name="$(basename "$crate")"
  toml="${crate}Cargo.toml"
  [[ -f "$toml" ]] || continue
  desc="$(grep -m1 '^description' "$toml" | sed -E 's/^description = "(.*)"$/\1/')"
  pkg="$(grep -m1 '^name' "$toml" | sed -E 's/^name = "(.*)"$/\1/')"
  ver="$(grep -m1 '^version' "$toml" | sed -E 's/^version = "(.*)"$/\1/')"
  lic="$(grep -m1 '^license' "$toml" | sed -E 's/^license = "(.*)"$/\1/' || true)"
  ts=$( (grep -rcE '^#\[test\]' "${crate}src/" 2>/dev/null || true) | awk -F: '{s+=$2} END {print s+0}')

  out="${crate}README.md"
  # Preserve hand-rolled READMEs unless they carry our marker.
  if [[ -f "$out" ]] && ! grep -qF "$MARKER" "$out"; then
    echo "skip (hand-rolled): $out"
    continue
  fi

  cat >"$out" <<EOF
# ${pkg}

${desc}

${MARKER}

| | |
|---|---|
| **Version** | \`${ver}\` |
| **License** | \`${lic}\` |
| **Unit tests** | ${ts} |
| **Source** | [\`crates/${name}/src/lib.rs\`](src/lib.rs) |

## Architecture

\`${pkg}\` is a pure-data Rust crate — no IO, no DOM. The host
(\`crates/strivo-web/\`) wires it to a Pro-gated HTTP endpoint and
surfaces the result on the SPA.

The crate's responsibility is:

1. Provide typed model(s) that describe what the plugin produces or
   consumes (see \`src/lib.rs\` for the public surface).
2. Compose pure transformations on those models — filter builders,
   parsers, geometry, scoring, ranking — that can be unit-tested
   without any external runtime.
3. Stay decoupled from ffmpeg, SQLite, IPC, HTTP — those live in the
   host. The crate's signature surface is just types + functions
   over them.

## Testing

\`\`\`bash
cargo test -p ${pkg}
\`\`\`

## Capability tags

See the marketplace manifest in
\`crates/marketplace/src/lib.rs::default_catalog()\` for the
canonical capability tags this plugin produces / consumes and the
DAW-vision \`x.\`-prefixed extensions.
EOF
  echo "wrote: $out"
done
